{% set name = "py_ecc" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py_ecc-{{ version }}.tar.gz
  sha256: 557461f42e57294d734305a30faf6b8903421651871e9cdeff8d8e67c6796c70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - eth-typing >=3.0.0
    - eth-utils >=2.0.0
    - cached-property >=1.5.1
    
test:
  imports:
    - py_ecc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ethereum/py_ecc
  summary: 'py-ecc: Elliptic curve crypto in python including secp256k1, alt_bn128, and bls12_381'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
